# Generated by Django 4.2.13 on 2026-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_bill_due_date_transaction_bill_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bill_status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bill_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
